version: '3.8'

services:
  app:
    # Build the image from the Dockerfile in the current directory
    build:.
    # Name the container for easier identification
    container_name: logistics_predictor_app
    # Set the working directory inside the container
    working_dir: /app
    # Command to run when the container starts
    command: ["python", "main.py"]
    # Pass environment variables from a '.env' file securely
    env_file:
      -.env
    # Restart policy
    restart: unless-stopped
