name: logistics-carrier-prediction-tool
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - joblib
  - pip
  - pip:
      - anvil-uplink
      - python-dotenv
      - plotly