name: logistics-carrier-prediction-tool
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn=1.7.1
  - matplotlib
  - seaborn
  - jupyterlab
  - joblib
  - pip
  - pip:
      - anvil-uplink
      - plotly
      - pycountry